name: Deploy to Azure

on:
  push:
    branches:
      - main  # Change this if your main branch has a different name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_location: "/"  # Update if your app is inside a subfolder
          api_location: ""
          output_location: "dist"  # Adjust based on your build system
